#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
from os.path import split
import argparse
import pandas as pd
from math import radians, cos, sin, asin, sqrt


# Import from mlproject
import mlproject
from mlproject.lib import clean_data


def return_number(number):
    return f"congratulations, your number is {number}"



if __name__ == '__main__':
    usage = '%(prog)s'
    description = 'enter a number'
    # https://docs.python.org/3/library/argparse.html
    # https://docs.python.org/3/howto/argparse.html
    parser = argparse.ArgumentParser(description=description, usage=usage)
    parser.add_argument('number', type=int, help='number')
    args = parser.parse_args()
    return_number(args.number)
